version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: vaultpay-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vaultpay
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init-scripts:/docker-entrypoint-initdb.d
  redis:
    image: redis:7-alpine
    container_name: vaultpay-redis
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: vaultpay-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pgdata:
